### ISSUE TITLE
AzureAD Group Filter problem

### ISSUE THREAD

**Issue by maddeus1988** [rubrikinc/microsoft-365-sizing#13]
Hi

we have tryed to execute the script with AzureAD Group filter but if we send 

 ./Get-RubrikM365SizingInfo.ps1 -AzureAdGroupName "grp_rubrik_365"

We always get the complete tenant in the output
 
 We also tryed ./Get-RubrikM365SizingInfo.ps1 -AzureAdGroupName "grp_rubrik_365@>domain<"

Same result

Kind regards
Matthias
![m365_ADgroup_Problem](https://github.com/rubrikinc/microsoft-365-sizing/assets/139244388/98a761fc-b912-46a1-a368-720688a7091a)

**Comment by sujeet** [comment]
@maddeus1988 Thanks for reporting the issue!
It has been fixed in https://github.com/rubrikinc/microsoft-365-sizing/pull/14
